"""Golden parity tests for the numpy-only decoder.

The golden.bin bundle (generated by the cw-train repo) pins the PyTorch
reference outputs. The decoder must reproduce p within 5e-4 and decode text
byte-for-byte on all six clips — the same contract as the Go decoder.

Run:  python tests/test_decoder.py   (no pytest needed)
CI:   pytest tests/
"""
import os
import struct
import sys
import wave

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

import numpy as np

from pycw.decoder import Decoder, decode_wav, decode_bytes, model_bytes, load_weights, NPModel
from pycw.decoder.rules import decode_runs
from pycw.decoder.features import extract_features, detect_tone

SR = 16000
GOLDEN = os.path.join(os.path.dirname(__file__), "data", "golden.bin")


def load_golden():
    raw = open(GOLDEN, "rb").read()
    assert raw[:4] == b"CWGB"
    n = struct.unpack("<q", raw[4:12])[0]
    pos = 12
    clips = []
    for _ in range(n):
        ln = struct.unpack("<i", raw[pos:pos + 4])[0]; pos += 4
        text = raw[pos:pos + ln].decode(); pos += ln
        sr, tone = struct.unpack("<dd", raw[pos:pos + 16]); pos += 16
        nw = struct.unpack("<q", raw[pos:pos + 8])[0]; pos += 8
        wav = np.frombuffer(raw[pos:pos + 4 * nw], dtype=np.float32); pos += 4 * nw
        f0 = struct.unpack("<d", raw[pos:pos + 8])[0]; pos += 8
        nf = struct.unpack("<q", raw[pos:pos + 8])[0]; pos += 8
        F = np.frombuffer(raw[pos:pos + 4 * nf], dtype=np.float32).reshape(-1, 6)
        pos += 4 * nf
        np_ = struct.unpack("<q", raw[pos:pos + 8])[0]; pos += 8
        p = np.frombuffer(raw[pos:pos + 4 * np_], dtype=np.float32)
        pos += 4 * np_
        ol = struct.unpack("<i", raw[pos:pos + 4])[0]; pos += 4
        out = raw[pos:pos + ol].decode(); pos += ol
        clips.append(dict(text=text, sr=sr, wav=wav, f0=f0, F=F, p=p, out=out))
    return clips


def test_no_torch_imported():
    assert "torch" not in sys.modules, "decoder must not import torch"


def test_forward_matches_golden():
    model = NPModel(load_weights(model_bytes()))
    for i, c in enumerate(load_golden()):
        p = model.forward(c["F"])
        d = np.abs(p - c["p"]).max()
        assert d < 5e-4, f"clip {i}: p diff {d:.2e}"


def test_full_pipeline_matches_golden_text():
    dec = Decoder()
    for i, c in enumerate(load_golden()):
        out = dec.decode(c["wav"], c["sr"])
        assert out == c["out"], f"clip {i}: {out!r} != {c['out']!r}"


def test_wav_roundtrip():
    dec = Decoder()
    for i, c in enumerate(load_golden()):
        pcm = (np.clip(c["wav"], -1, 1) * 32767).astype(np.int16)
        path = f"/tmp/cw_pycw_test_{i}.wav"
        with wave.open(path, "wb") as w:
            w.setnchannels(1)
            w.setsampwidth(2)
            w.setframerate(int(c["sr"]))
            w.writeframes(pcm.tobytes())
        try:
            out = decode_wav(path, decoder=dec)
            assert out == c["out"], f"wav clip {i}: {out!r} != {c['out']!r}"
        finally:
            os.unlink(path)


def test_decode_bytes():
    dec = Decoder()
    c = load_golden()[3]
    pcm = (np.clip(c["wav"], -1, 1) * 32767).astype(np.int16).tobytes()
    out = decode_bytes(pcm, sample_rate=int(c["sr"]), decoder=dec)
    assert out == c["out"]


def test_auto_tone_detection():
    dec = Decoder()
    c = load_golden()[0]
    f0 = detect_tone(c["wav"], int(c["sr"]))
    assert abs(f0 - c["f0"]) < 1.0


def test_generate_then_decode_roundtrip():
    """pycw generates -> pycw decodes (locks the 16k silence-rate fix)."""
    import pycw
    path = "/tmp/cw_pycw_rt.wav"
    text = "cq cq de bd8cmn pse k"
    pycw.output_wave(path, text, 20, 700, 1.0, 16000)
    try:
        out = decode_wav(path)
        assert out == text, f"{out!r} != {text!r}"
    finally:
        os.unlink(path)


if __name__ == "__main__":
    for name, fn in sorted(globals().items()):
        if name.startswith("test_") and callable(fn):
            fn()
            print(f"{name}: PASS")
    print("all tests passed")